### ISSUE TITLE
Make `npm start` also `watch` the sources (or have `npm watch`)

### ISSUE THREAD

**Issue by jeantil** [lyontechhub/lyontechhub.github.io#53]
It would be nice for developers working on the site to have a simple way to run both `server.js` and `grunt watch` 
Either by changing the existing `npm start` command or by creating a `npm watch` command. I am completely unsure how to get that working and will continue using my workaround with background jobs for now but it feels klunky :(

**Comment by snapeuh** [comment]
@jeantil Now you can do `npm run dev` to both run the dev server and watch the files.

**Comment by jeantil** [comment]
thank you

**Comment by jeantil** [comment]
probably unrelated but
```
$ npm --version
3.10.9
$ node --version
v7.2.1
$ npm run dev

> LyonTechHub@0.1.0 dev /Users/jean/dev/websites/lyontechhub.github.io
> gulp dev

module.js:472
    throw err;
    ^

Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at evalmachine.<anonymous>:17:20
    at Object.<anonymous> (/Users/jean/dev/websites/lyontechhub.github.io/node_modules/gulp/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:11:8)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
$ nvm use 6.8
Now using node v6.8.1 (npm v3.10.8)
$ npm run dev

> LyonTechHub@0.1.0 dev /Users/jean/dev/websites/lyontechhub.github.io
> gulp dev

(node:85622) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:85622) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:85622) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:85622) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[14:11:51] Using gulpfile ~/dev/websites/lyontechhub.github.io/gulpfile.js
``` 

setting up a [`.nvmrc`](https://github.com/creationix/nvm#nvmrc) could be nice
