### ISSUE TITLE
Prerender error: TypeError: parsedQuery.hasOwnProperty is not a function

### ISSUE THREAD

**Issue by StephaneColson** [lyontechhub/lyontechhub.github.io#84]
I have this when trying to access a local `npm start` instance:

> TypeError: parsedQuery.hasOwnProperty is not a function
    at Function.prerender.shouldShowPrerenderedPage (/Users/stephane/Documents/GitHub/lyontechhub.github.io/node_modules/prerender-node/index.js:128:33)
    at module.exports (/Users/stephane/Documents/GitHub/lyontechhub.github.io/node_modules/prerender-node/index.js:6:17)
    at Layer.handle [as handle_request] (/Users/stephane/Documents/GitHub/lyontechhub.github.io/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/stephane/Documents/GitHub/lyontechhub.github.io/node_modules/express/lib/router/index.js:317:13)
    at /Users/stephane/Documents/GitHub/lyontechhub.github.io/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/stephane/Documents/GitHub/lyontechhub.github.io/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/stephane/Documents/GitHub/lyontechhub.github.io/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/Users/stephane/Documents/GitHub/lyontechhub.github.io/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/Users/stephane/Documents/GitHub/lyontechhub.github.io/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/stephane/Documents/GitHub/lyontechhub.github.io/node_modules/express/lib/router/index.js:317:13)
TypeError: parsedQuery.hasOwnProperty is not a function
    at Function.prerender.shouldShowPrerenderedPage (/Users/stephane/Documents/GitHub/lyontechhub.github.io/node_modules/prerender-node/index.js:128:33)
    at module.exports (/Users/stephane/Documents/GitHub/lyontechhub.github.io/node_modules/prerender-node/index.js:6:17)
    at Layer.handle [as handle_request] (/Users/stephane/Documents/GitHub/lyontechhub.github.io/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/stephane/Documents/GitHub/lyontechhub.github.io/node_modules/express/lib/router/index.js:317:13)
    at /Users/stephane/Documents/GitHub/lyontechhub.github.io/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/stephane/Documents/GitHub/lyontechhub.github.io/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/stephane/Documents/GitHub/lyontechhub.github.io/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/Users/stephane/Documents/GitHub/lyontechhub.github.io/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/Users/stephane/Documents/GitHub/lyontechhub.github.io/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/stephane/Documents/GitHub/lyontechhub.github.io/node_modules/express/lib/router/index.js:317:13)

Environment:
- MacOS 10.12.5 + Chrome or Safari
- prerender 1.3.0
- node v6.11.0

Maybe that according to [this](https://github.com/prerender/prerender-node/issues/123) a newer version of prerender should be used. WDYT?

**Comment by fpellet** [comment]
Merged \o/
Thanks
